---

- name: "[DOCKER] Create docker directories"
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
  loop:
    - path: "/home/{{ ansible_user }}/.docker"
      owner: "{{ ansible_user }}"
    - path: "/etc/docker"
      owner: root

- name: "[DOCKER] create daemon.json"
  become: true
  become_method: sudo
  copy:
    content: |
      {
        "insecure-registries": {{ docker_registries | selectattr('insecure', 'defined') | map(attribute='name') | to_json }}
      }
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root

- name: "[DOCKER] Restart docker"
  become: true
  become_method: sudo
  systemd:
    name: docker
    state: restarted
