Vagrant.configure("2") do |config|
  ################################################################
  #                    COMMON CONFIGURATION                      #
  ################################################################

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 2
    v.customize ["modifyvm", :id, "--usb", "on"]
    v.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  ################################################################
  #                          INSTANCES                           #
  ################################################################

  config.vm.define 'mint' do |node|
    node.vm.box = "boxcycler/linuxmint-19-cinnamon-64bit-v2-release"
    node.vm.network :private_network, ip: "192.168.56.200"
  end

  config.vm.define 'kubuntu' do |node|
    node.vm.box = "aazario/kubuntu-bionic64"
    node.vm.network :private_network, ip: "192.168.56.203"
  end

  config.vm.define 'ubuntu' do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.network :private_network, ip: "192.168.56.201"
  end

  config.vm.define 'xubuntu' do |node|
    node.vm.box = "kevinwortman/xubuntu-bionic"
    node.vm.network :private_network, ip: "192.168.56.206"
  end

  config.vm.define 'fedora30' do |node|
    node.vm.box = "bento/fedora-30"
    node.vm.network :private_network, ip: "192.168.56.202"
  end

  config.vm.define 'fedora31' do |node|
    node.vm.box = "bento/fedora-31"
    node.vm.network :private_network, ip: "192.168.56.205"
  end

  config.vm.define 'fedora32' do |node|
    node.vm.box = "bento/fedora-32"
    node.vm.network :private_network, ip: "192.168.56.209"
  end

  config.vm.define 'fedora33' do |node|
    node.vm.box = "bento/fedora-33"
    node.vm.network :private_network, ip: "192.168.56.210"
  end

  config.vm.define 'fedora34' do |node|
    node.vm.box = "bento/fedora-34"
    node.vm.network :private_network, ip: "192.168.56.211"
  end

  config.vm.define 'fedora35' do |node|
    node.vm.box = "bento/fedora-35"
    node.vm.network :private_network, ip: "192.168.56.212"
  end

  config.vm.define 'arch' do |node|
    node.vm.box = "austinbutler/archlinux-gui-x86_64"
    node.vm.network :private_network, ip: "192.168.56.204"
  end

  config.vm.define 'manjaro' do |node|
    node.vm.box = "amigcamel/manjaro-gnome-18.0.4"
    node.vm.network :private_network, ip: "192.168.56.207"
  end

  config.vm.define 'debian' do |node|
    node.vm.box = "debian/buster64"
    node.vm.network :private_network, ip: "192.168.56.208"
  end
end
