---

- name: "[MEGASYNC] [FEDORA] Add MEGASYNC repository"
  copy:
    dest: /etc/yum.repos.d/megasync.repo
    content: |
      [MEGAsync]
      name=MEGAsync
      baseurl=https://mega.nz/linux/repo/Fedora_$releasever/
      gpgkey=https://mega.nz/linux/repo/Fedora_$releasever/repodata/repomd.xml.key
      gpgcheck=1
      enabled=1
    mode: 0640

- name: "[MEGASYNC] [FEDORA] install megasync package"
  dnf:
    name: "{{ megasync_package }}"
    state: present
    update_cache: true
    disable_gpg_check: true

- name: "[MEGASYNC] [FEDORA] Install megasync for file manager"
  dnf:
    name: "{{ file_manager_plugin }}"
    state: present
    disable_gpg_check: true
  when: file_manager_plugin is defined
